SET foreign_key_checks = 0;

DELETE FROM `spring`.`activity`;
DELETE FROM `spring`.`forum_posts`;
DELETE  FROM `spring`.`vaccinationappointments`;
DELETE FROM `spring`.`users`;

INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('000', 'address', 'BvgDXSOne0f4fAdS7ym+FQ==', 'Irish', 'andy', 'test', 'user@gmail.com', '$2a$10$T1jECG.JGCwZ1m0MWKne6e9kYNda04cJP6da7.nbBVXiqAth8zdz6', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==', 0, '0'); 
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('575', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'Welsh', 'andy', 'test', '575@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0'); 
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('440', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'Irish', 'andy', 'test', '440@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0'); 
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('81', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'Irish', 'andy', 'test', '81@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0'); 
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('487', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'Welsh', 'andy', 'test', '487@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0'); 
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('386', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'Irish', 'andy', 'test', '386@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0'); 
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('817', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'Dutch', 'andy', 'test', '817@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0'); 
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('63', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'Irish', 'andy', 'test', '63@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0'); 
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('935', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'Dutch', 'andy', 'test', '935@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0'); 
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('793', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'English', 'andy', 'test', '793@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0');
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('370', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'Welsh', 'andy', 'test', '370@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0');
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('945', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'Dutch', 'andy', 'test', '945@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0');
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('261', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'Irish', 'andy', 'test', '261@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0');
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('528', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'Irish', 'andy', 'test', '528@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0');
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('627', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'English', 'andy', 'test', '627@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0');
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('19', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'Welsh', 'andy', 'test', '19@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0');
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('847', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'Welsh', 'andy', 'test', '847@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0');
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('234', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'Irish', 'andy', 'test', '234@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0');
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('582', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'Irish', 'andy', 'test', '582@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0');
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('280', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'Irish', 'andy', 'test', '280@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0');
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('144', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'Dutch', 'andy', 'test', '144@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0');
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('296', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'Dutch', 'andy', 'test', '296@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0');
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('498', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'Irish', 'andy', 'test', '498@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0');
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('416', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'English', 'andy', 'test', '416@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0');
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('583', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'English', 'andy', 'test', '583@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0');
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('830', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'English', 'andy', 'test', '830@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0');
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('953', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'Welsh', 'andy', 'test', '953@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0');
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('236', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'Welsh', 'andy', 'test', '236@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0');
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('837', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'Irish', 'andy', 'test', '837@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0');
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('701', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'Dutch', 'andy', 'test', '701@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0');
INSERT INTO `spring`.`users` (`id`,`address`, `dob`, `nationality`, `first_name`, `last_name`, `email`, `password`, `phone_number`, `pps`,`account_locked` ,`attempts`) VALUES ('688', 'address', '48fDphe6HAFcjM+9XuiUeQ==', 'English', 'andy', 'test', '688@gmail.com', '$2a$10$pm49cJBcHghhHFno10rdguO5zjsen.tZmERPb/teHfit6G4BXiwyK', '6wtmnWZnZtV1dR9vaHomVg==', '06o1LT1yeZVdj365xLmJKA==',0, '0');

INSERT INTO `spring`.`vaccinationappointments` (`id`, `brand_type`, `dose_number`, `time_slot`, `user_id`, `vaccination_centre`) VALUES ('1', 'Moderna', '1', '09:45 2022-05-14', '261', 'City West');
INSERT INTO `spring`.`vaccinationappointments` (`id`, `brand_type`, `dose_number`, `time_slot`, `user_id`, `vaccination_centre`) VALUES ('2', 'Pfizer', '2', '09:45 2022-05-21', '261', 'Blanchardstown Hospital');

SET foreign_key_checks = 1;